# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
          name: "various-utils.jar"
          path: "./build/libs/various-utils-1.0.jar"

    - name: Upload a Build Artifact 1
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "various-utils-sources.jar"
        path: "./build/libs/various-utils-1.0-sources.jar"

    - name: Upload a Build Artifact 2
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "various-utils-javadoc.jar"
        path: "./build/libs/various-utils-1.0-javadoc.jar"

  publish:
    name: "publish-release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
            files: ./*.jar
            tag_name: v${{ github.run_number }}
            name: Release V${{ github.run_number }}